VAGRANT_DEFAULT_PROVIDER = "libvirt"

Vagrant.configure("2") do |config|

  config.env.enable

  # Workaround for Vagrant issue with TTY errors - copied from
  # https://superuser.com/questions/1160025/how-to-solve-ttyname-failed-inappropriate-ioctl-for-device-in-vagrant
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  #config.disksize.size = ENV['DISKSPACE']

  config.vm.define "provider" do |provider|
    provider.vm.box = ENV['BOXNAME']

    provider.vm.provider "virtualbox" do |v|
      v.memory = ENV['MEMORY']
      # Synchronize clock in one step if difference is more than 1000 ms / 1s
      # Copied from https://stackoverflow.com/questions/19490652/how-to-sync-time-on-host-wake-up-within-virtualbox
      v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ]
    end

    provider.vm.provider :libvirt do |libvirt|
      libvirt.driver = "kvm"
      libvirt.memory = ENV['MEMORY']
    end

    provider.vm.provision "file", source: ".env", destination: "/tmp/irods-test.env"
    provider.vm.provision "file", source: "../_common/common_functions.sh", destination: "/tmp/common_functions.sh"
    provider.vm.provision "file", source: "../_common/provider-unattended-install.irods-4.3.template", destination: "/tmp/provider-unattended-install.irods-4.3.template"
    provider.vm.provision "file", source: "../_common/irods.rsyslog", destination: "/tmp/irods.rsyslog"
    provider.vm.provision "file", source: "../_common/irods.logrotate", destination: "/tmp/irods.logrotate"
    provider.vm.provision :shell, :path => '../_common/update-ipv6-settings.sh', :args => "/tmp/irods-test.env"
    provider.vm.provision :shell, :path => '../_common/initialize-network-settings.sh', :args => "/tmp/irods-test.env"
    provider.vm.provision :shell, :path => '../_common/install-irods-provider.sh', :args => "/tmp/irods-test.env"

  end

end
