Vagrant.configure("2") do |config|

  config.env.enable

  # Workaround for Vagrant issue with TTY errors - copied from
  # https://superuser.com/questions/1160025/how-to-solve-ttyname-failed-inappropriate-ioctl-for-device-in-vagrant
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.disksize.size = ENV['DISKSPACE']

  config.vm.define "provider" do |provider|
    provider.vm.box = ENV['BOXNAME']
    provider.vm.provider "virtualbox" do |v|
      v.memory = ENV['PROVIDER_MEMORY']
      # Synchronize clock in one step if difference is more than 1000 ms / 1s
      # Copied from https://stackoverflow.com/questions/19490652/how-to-sync-time-on-host-wake-up-within-virtualbox
      v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ]
    end
    provider.vm.provision "file", source: ".env", destination: "/tmp/irods-test.env"
    provider.vm.provision :shell, :path => '../_common/update-ipv6-settings.sh', :args => "/tmp/irods-test.env"
    provider.vm.provision :shell, :path => '../_common/initialize-hosts-file.sh', :args => "/tmp/irods-test.env"
    provider.vm.provision :shell, :path => '../_common/initialize-network-settings.sh', :args => "/tmp/irods-test.env"
    provider.vm.provision :shell, :path => '../_common/install-irods-provider.sh', :args => "/tmp/irods-test.env"
    provider.vm.network "private_network", ip: ENV['PROVIDER_IP']
  end

  config.vm.define "consumer" do |consumer|
    consumer.vm.box = ENV['BOXNAME']
    consumer.vm.provider "virtualbox" do |v|
      v.memory = ENV['CONSUMER_MEMORY']
      # Synchronize clock in one step if difference is more than 1000 ms / 1s
      # Copied from https://stackoverflow.com/questions/19490652/how-to-sync-time-on-host-wake-up-within-virtualbox
      v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ]
    end
    consumer.vm.provision "file", source: ".env", destination: "/tmp/irods-test.env"
    consumer.vm.provision :shell, :path => '../_common/update-ipv6-settings.sh', :args => "/tmp/irods-test.env"
    consumer.vm.provision :shell, :path => '../_common/initialize-hosts-file.sh' , :args => "/tmp/irods-test.env"
    consumer.vm.provision :shell, :path => '../_common/initialize-network-settings.sh', :args => "/tmp/irods-test.env"
    consumer.vm.provision :shell, :path => '../_common/install-irods-consumer.sh', :args => "/tmp/irods-test.env"
    consumer.vm.network "private_network", ip: ENV['CONSUMER_IP']
  end

end
